name: Expo EAS Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      # Log in to Expo using GitHub Secrets
      - name: Expo login
        run: eas login --username ${{ secrets.EXPO_USERNAME }} --password ${{ secrets.EXPO_PASSWORD }}

      - name: EAS Build Android Configure
        run: eas build --platform android

      - name: Build Android APK
        run: eas build --platform android --profile preview

      - name: Show Android Build URL
        run: echo "Android preview https://expo.dev/accounts/${{ secrets.EXPO_USERNAME }}/projects/github-action/builds/latest"
